### ISSUE TITLE
Unused signal.h library

### ISSUE THREAD

**Issue by noraj** [yorickdewid/Chat-Server-Secure#2]
Hello,

why do you use `signal.h` ?

I didn't see any Library Variables (sig_atomic_t), Library Macros (SIG_DFL, SIG_ERR, SIG_IGN,  SIGABRT, SIGFPE, SIGILL, SIGINT, SIGSEGV, SIGTERM) or any Library Functions (void (_signal(int sig, void (_func)(int)))(int), int raise(int sig)).

So the Library seems unused to me.

**Comment by yorickdewid** [comment]
Probably left over from earlier tests. Thx.

Fixed in 6947c316a76f30facd29a56bebd23a901c85c8d9
